### ISSUE TITLE
touchdrag?

### ISSUE THREAD

**Issue by KyleAMathews** [tleunen/react-clickdrag#1]
Just curious if you've thought about adding support for touch events as well.

**Comment by tleunen** [comment]
That could be a nice feature, yep. Not sure what would be the best way to do it though.
Clicking on the element, and then sliding? Or just remove the custom behavior and replace everything with a basic number input?

**Comment by KyleAMathews** [comment]
The first would be cooler but harder. The latter would be a great start.

**Comment by tleunen** [comment]
It's just that I'm not sure about the best behavior with the touch. Usually I'm not a fan of number input when I'm using a tablet. So maybe transform it as a slider (range input) ?

**Comment by KyleAMathews** [comment]
That sounds great — [support is pretty good](http://caniuse.com/#search=range)

**Comment by tleunen** [comment]
Omg I'm sorry. I thought we were in the `react-number-editor` repo :/
So yes, `react-clickdrag` should have touch features ;)

**Comment by tleunen** [comment]
I've update the code. I completely rewrote the code to be a react component instead of a mixin.
And I added an option to enable `touch` events.
This is now version 2.0.0
